# Generated by Django 5.2.2 on 2025-08-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
