# Generated by Django 5.2.2 on 2025-08-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_alter_booking_user'),
        ('tourism', '0011_alter_booking_booking_date'),
    ]

    operations = [
    ]
