# Generated by Django 5.2.2 on 2025-09-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_heritagesite_heritagetour_heritagetourbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
