# Generated by Django 5.2.2 on 2025-09-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
